var hierarchy =
[
    [ "c3_param_at_tleaf", "structc3__param__at__tleaf.html", null ],
    [ "c3_temperature_response_parameters", "structc3__temperature__response__parameters.html", null ],
    [ "canopy_photosynthesis_outputs", "structcanopy__photosynthesis__outputs.html", null ],
    [ "collatz_result", "structcollatz__result.html", null ],
    [ "crop_phenology", "structcrop__phenology.html", null ],
    [ "dbp_str", "structdbp__str.html", null ],
    [ "differential_module", null, [
      [ "aba_decay", "classstandard_b_m_l_1_1aba__decay.html", null ],
      [ "bucket_soil_drainage", "classstandard_b_m_l_1_1bucket__soil__drainage.html", null ],
      [ "cumulative_carbon_dynamics", "classstandard_b_m_l_1_1cumulative__carbon__dynamics.html", null ],
      [ "cumulative_water_dynamics", "classstandard_b_m_l_1_1cumulative__water__dynamics.html", null ],
      [ "development_index", "classstandard_b_m_l_1_1development__index.html", null ],
      [ "example_model_partitioning", "classstandard_b_m_l_1_1example__model__partitioning.html", null ],
      [ "grimm_soybean_flowering", "classstandard_b_m_l_1_1grimm__soybean__flowering.html", null ],
      [ "harmonic_oscillator", "classstandard_b_m_l_1_1harmonic__oscillator.html", null ],
      [ "magic_clock", "classstandard_b_m_l_1_1magic__clock.html", null ],
      [ "maintenance_respiration", "classstandard_b_m_l_1_1maintenance__respiration.html", null ],
      [ "night_and_day_trackers", "classstandard_b_m_l_1_1night__and__day__trackers.html", null ],
      [ "nr_ex", "classstandard_b_m_l_1_1nr__ex.html", null ],
      [ "one_layer_soil_profile", "classstandard_b_m_l_1_1one__layer__soil__profile.html", null ],
      [ "one_layer_soil_profile_derivatives", "classstandard_b_m_l_1_1one__layer__soil__profile__derivatives.html", null ],
      [ "partitioning_growth", "classstandard_b_m_l_1_1partitioning__growth.html", null ],
      [ "phase_clock", "classstandard_b_m_l_1_1phase__clock.html", null ],
      [ "poincare_clock", "classstandard_b_m_l_1_1poincare__clock.html", null ],
      [ "senescence_logistic", "classstandard_b_m_l_1_1senescence__logistic.html", null ],
      [ "song_flowering", "classstandard_b_m_l_1_1song__flowering.html", null ],
      [ "thermal_time_and_frost_senescence", "classstandard_b_m_l_1_1thermal__time__and__frost__senescence.html", null ],
      [ "thermal_time_beta", "classstandard_b_m_l_1_1thermal__time__beta.html", null ],
      [ "thermal_time_bilinear", "classstandard_b_m_l_1_1thermal__time__bilinear.html", null ],
      [ "thermal_time_linear", "classstandard_b_m_l_1_1thermal__time__linear.html", null ],
      [ "thermal_time_linear_extended", "classstandard_b_m_l_1_1thermal__time__linear__extended.html", null ],
      [ "thermal_time_senescence", "classstandard_b_m_l_1_1thermal__time__senescence.html", null ],
      [ "thermal_time_trilinear", "classstandard_b_m_l_1_1thermal__time__trilinear.html", null ],
      [ "two_layer_soil_profile", "classstandard_b_m_l_1_1two__layer__soil__profile.html", null ]
    ] ],
    [ "direct_module", null, [
      [ "FvCB", "classstandard_b_m_l_1_1_fv_c_b.html", null ],
      [ "Module_1", "classstandard_b_m_l_1_1_module__1.html", null ],
      [ "Module_2", "classstandard_b_m_l_1_1_module__2.html", null ],
      [ "Module_3", "classstandard_b_m_l_1_1_module__3.html", null ],
      [ "ball_berry", "classstandard_b_m_l_1_1ball__berry.html", null ],
      [ "biomass_leaf_n_limitation", "classstandard_b_m_l_1_1biomass__leaf__n__limitation.html", null ],
      [ "broyden_test", "classstandard_b_m_l_1_1broyden__test.html", null ],
      [ "buck_swvp", "classstandard_b_m_l_1_1buck__swvp.html", null ],
      [ "c3_assimilation", "classstandard_b_m_l_1_1c3__assimilation.html", null ],
      [ "c3_canopy", "classstandard_b_m_l_1_1c3__canopy.html", null ],
      [ "c3_leaf_photosynthesis", "classstandard_b_m_l_1_1c3__leaf__photosynthesis.html", null ],
      [ "c3_parameters", "classstandard_b_m_l_1_1c3__parameters.html", null ],
      [ "c4_assimilation", "classstandard_b_m_l_1_1c4__assimilation.html", null ],
      [ "c4_canopy", "classstandard_b_m_l_1_1c4__canopy.html", null ],
      [ "c4_leaf_photosynthesis", "classstandard_b_m_l_1_1c4__leaf__photosynthesis.html", null ],
      [ "canopy_gbw_thornley", "classstandard_b_m_l_1_1canopy__gbw__thornley.html", null ],
      [ "carbon_assimilation_to_biomass", "classstandard_b_m_l_1_1carbon__assimilation__to__biomass.html", null ],
      [ "daylength_calculator", "classstandard_b_m_l_1_1daylength__calculator.html", null ],
      [ "development_index_from_thermal_time", "classstandard_b_m_l_1_1development__index__from__thermal__time.html", null ],
      [ "example_model_mass_gain", "classstandard_b_m_l_1_1example__model__mass__gain.html", null ],
      [ "fake_solar", "classstandard_b_m_l_1_1fake__solar.html", null ],
      [ "format_time", "classstandard_b_m_l_1_1format__time.html", null ],
      [ "golden_ratio_hyperbola", "classstandard_b_m_l_1_1golden__ratio__hyperbola.html", null ],
      [ "grimm_soybean_flowering_calculator", "classstandard_b_m_l_1_1grimm__soybean__flowering__calculator.html", null ],
      [ "harmonic_energy", "classstandard_b_m_l_1_1harmonic__energy.html", null ],
      [ "height_from_lai", "classstandard_b_m_l_1_1height__from__lai.html", null ],
      [ "hyperbola_2d", "classstandard_b_m_l_1_1hyperbola__2d.html", null ],
      [ "incident_shortwave_from_ground_par", "classstandard_b_m_l_1_1incident__shortwave__from__ground__par.html", null ],
      [ "leaf_evapotranspiration", "classstandard_b_m_l_1_1leaf__evapotranspiration.html", null ],
      [ "leaf_evapotranspiration_check", "classstandard_b_m_l_1_1leaf__evapotranspiration__check.html", null ],
      [ "leaf_gbw_campbell", "classstandard_b_m_l_1_1leaf__gbw__campbell.html", null ],
      [ "leaf_gbw_nikolov", "classstandard_b_m_l_1_1leaf__gbw__nikolov.html", null ],
      [ "leaf_shape_factor", "classstandard_b_m_l_1_1leaf__shape__factor.html", null ],
      [ "leaf_water_stress_exponential", "classstandard_b_m_l_1_1leaf__water__stress__exponential.html", null ],
      [ "light_from_solar", "classstandard_b_m_l_1_1light__from__solar.html", null ],
      [ "linear_vmax_from_leaf_n", "classstandard_b_m_l_1_1linear__vmax__from__leaf__n.html", null ],
      [ "litter_cover", "classstandard_b_m_l_1_1litter__cover.html", null ],
      [ "maintenance_respiration_calculator", "classstandard_b_m_l_1_1maintenance__respiration__calculator.html", null ],
      [ "multilayer_canopy_integrator", "classstandard_b_m_l_1_1multilayer__canopy__integrator.html", [
        [ "ten_layer_canopy_integrator", "classstandard_b_m_l_1_1ten__layer__canopy__integrator.html", null ]
      ] ],
      [ "multilayer_canopy_photosynthesis< canopy_module_type, leaf_module_type >", "classstandard_b_m_l_1_1multilayer__canopy__photosynthesis.html", [
        [ "ten_layer_c3_canopy", "classstandard_b_m_l_1_1ten__layer__c3__canopy.html", null ],
        [ "ten_layer_c4_canopy", "classstandard_b_m_l_1_1ten__layer__c4__canopy.html", null ],
        [ "ten_layer_rue_canopy", "classstandard_b_m_l_1_1ten__layer__rue__canopy.html", null ]
      ] ],
      [ "multilayer_canopy_properties", "classstandard_b_m_l_1_1multilayer__canopy__properties.html", [
        [ "ten_layer_canopy_properties", "classstandard_b_m_l_1_1ten__layer__canopy__properties.html", null ]
      ] ],
      [ "oscillator_clock_calculator", "classstandard_b_m_l_1_1oscillator__clock__calculator.html", null ],
      [ "parameter_calculator", "classstandard_b_m_l_1_1parameter__calculator.html", null ],
      [ "partitioning_coefficient_logistic", "classstandard_b_m_l_1_1partitioning__coefficient__logistic.html", null ],
      [ "partitioning_coefficient_selector", "classstandard_b_m_l_1_1partitioning__coefficient__selector.html", null ],
      [ "partitioning_growth_calculator", "classstandard_b_m_l_1_1partitioning__growth__calculator.html", null ],
      [ "partitioning_growth_calculator_leaf_costs", "classstandard_b_m_l_1_1partitioning__growth__calculator__leaf__costs.html", null ],
      [ "penman_monteith_leaf_temperature", "classstandard_b_m_l_1_1penman__monteith__leaf__temperature.html", null ],
      [ "penman_monteith_transpiration", "classstandard_b_m_l_1_1penman__monteith__transpiration.html", null ],
      [ "priestley_transpiration", "classstandard_b_m_l_1_1priestley__transpiration.html", null ],
      [ "rasmussen_specific_heat", "classstandard_b_m_l_1_1rasmussen__specific__heat.html", null ],
      [ "rh_to_mole_fraction", "classstandard_b_m_l_1_1rh__to__mole__fraction.html", null ],
      [ "root_onedim_test", "classstandard_b_m_l_1_1root__onedim__test.html", null ],
      [ "rue_leaf_photosynthesis", "classstandard_b_m_l_1_1rue__leaf__photosynthesis.html", null ],
      [ "senescence_coefficient_logistic", "classstandard_b_m_l_1_1senescence__coefficient__logistic.html", null ],
      [ "shortwave_atmospheric_scattering", "classstandard_b_m_l_1_1shortwave__atmospheric__scattering.html", null ],
      [ "sla_linear", "classstandard_b_m_l_1_1sla__linear.html", null ],
      [ "sla_logistic", "classstandard_b_m_l_1_1sla__logistic.html", null ],
      [ "soil_evaporation", "classstandard_b_m_l_1_1soil__evaporation.html", null ],
      [ "soil_sunlight", "classstandard_b_m_l_1_1soil__sunlight.html", null ],
      [ "solar_position_michalsky", "classstandard_b_m_l_1_1solar__position__michalsky.html", null ],
      [ "soybean_development_rate_calculator", "classstandard_b_m_l_1_1soybean__development__rate__calculator.html", null ],
      [ "stefan_boltzmann_longwave", "classstandard_b_m_l_1_1stefan__boltzmann__longwave.html", null ],
      [ "stomata_water_stress_exponential", "classstandard_b_m_l_1_1stomata__water__stress__exponential.html", null ],
      [ "stomata_water_stress_linear", "classstandard_b_m_l_1_1stomata__water__stress__linear.html", null ],
      [ "stomata_water_stress_linear_and_aba_response", "classstandard_b_m_l_1_1stomata__water__stress__linear__and__aba__response.html", null ],
      [ "stomata_water_stress_sigmoid", "classstandard_b_m_l_1_1stomata__water__stress__sigmoid.html", null ],
      [ "thermal_time_development_rate_calculator", "classstandard_b_m_l_1_1thermal__time__development__rate__calculator.html", null ],
      [ "total_biomass", "classstandard_b_m_l_1_1total__biomass.html", null ],
      [ "total_growth_and_maintenance_respiration", "classstandard_b_m_l_1_1total__growth__and__maintenance__respiration.html", null ],
      [ "varying_Jmax25", "classstandard_b_m_l_1_1varying___jmax25.html", null ],
      [ "water_vapor_properties_from_air_temperature", "classstandard_b_m_l_1_1water__vapor__properties__from__air__temperature.html", null ]
    ] ],
    [ "energy_balance_outputs", "structenergy__balance__outputs.html", null ],
    [ "ET_Str", "struct_e_t___str.html", null ],
    [ "fixed_point_test_function", "structstandard_b_m_l_1_1fixed__point__test__function.html", null ],
    [ "frostParms", "structfrost_parms.html", null ],
    [ "FvCB_outputs", "struct_fv_c_b__outputs.html", null ],
    [ "Light_model", "struct_light__model.html", null ],
    [ "Light_profile", "struct_light__profile.html", null ],
    [ "crop_phenology::minerals1", "structcrop__phenology_1_1minerals1.html", null ],
    [ "module_library", "classstandard_b_m_l_1_1module__library.html", null ],
    [ "nitroParms", "structnitro_parms.html", null ],
    [ "photosynthesis_outputs", "structphotosynthesis__outputs.html", null ],
    [ "rd_str", "structrd__str.html", null ],
    [ "root_onedim_test::result", "structstandard_b_m_l_1_1root__onedim__test_1_1result.html", null ],
    [ "root_test_function", "structstandard_b_m_l_1_1root__test__function.html", null ],
    [ "seqRD_str", "structseq_r_d__str.html", null ],
    [ "soilML_str", "structsoil_m_l__str.html", null ],
    [ "stomata_outputs", "structstomata__outputs.html", null ],
    [ "ws_str", "structws__str.html", null ]
];