The BioCro C++ Library: /github/workspace/src/module_library/temperature_response_functions.h File Reference
temperature_response_functions.h File Reference
#include <cmath>
#include "../framework/constants.h"
Functions
double arrhenius_exponential (double c, double activation_energy, double temperature_k)
Calculates the exponential term of the Arrhenius equation.
double Q10_temperature_response (double temperature, double Tref)
A typical Q10-based temperature response. The two temperatures below must be supplied in the same units, but the units can be either K or degrees C.
double johnson_eyring_williams_response (double c, double Ha, double Hd, double S, double temperature_k)
A temperature response function originally defined in Johnson, Eyring, and Williams (1942), but used more recently to describe the temperature response of triose phosphate utilization limitations in Harley et al. (1992), Sharkey et al. (2007), and Yang et al. (2016).
double polynomial_response (double c0, double c1, double c2, double temperature_c)
A simple second-order polynomial equation describing the temperature response of a reaction rate or other parameter.
Function Documentation
arrhenius_exponential()
double arrhenius_exponential (double c, double activation_energy, double temperature_k) inline
Calculates the exponential term of the Arrhenius equation.
The Arrhenius equation gives the dependence of the rate constant of a chemical reaction on the absolute temperature and is often written as
‍k = A * e^(-E_a / R / T) (1)
where k is the rate constant, E_a is the activation energy, R is the ideal gas constant, and T is the absolute temperature. As T approaches infinity, E_a / R / T approaches zero and so k approaches A. Thus, A represents the rate constant in the limit of infinite temperature. From a practical standpoint, A is not a particularly useful parameter and for this reason it is often written as
‍A = k_0 * e^c (2)
where k_0 is the rate constant measured at a reference temperature (e.g. 25 degrees C) and c is a dimensionless parameter chosen so that k = k_0 at the reference temperature.
In order to make this function reusable, it only calculates the exponential factor, which is always dimensionless. I.e., it calculates e^(c - E_a / R / T).
Parameters
[in] c Dimensionless parameter related to the reference temperature at which the rate constant was measured
[in] activation_energy Activation energy of the reaction in J / mol
[in] temperature_k Absolute temperature in Kelvin
Returns
Return The Arrhenius exponential e^(c - E_a / R / T)
Definition at line 41 of file temperature_response_functions.h.
Referenced by c3_temperature_response(), and johnson_eyring_williams_response().
johnson_eyring_williams_response()
double johnson_eyring_williams_response (double c, double Ha, double Hd, double S, double temperature_k) inline
A temperature response function originally defined in Johnson, Eyring, and Williams (1942), but used more recently to describe the temperature response of triose phosphate utilization limitations in Harley et al. (1992), Sharkey et al. (2007), and Yang et al. (2016).
References:
Johnson, F. H., Eyring, H. & Williams, R. W. Journal of Cellular and Comparative Physiology 20, 247–268 (1942)
Harley, P. C., Thomas, R. B., Reynolds, J. F. & Strain, B. R. Plant, Cell & Environment 15, 271–282 (1992)
Sharkey, T. D., Bernacchi, C. J., Farquhar, G. D. & Singsaas, E. L. Plant, Cell & Environment 30, 1035–1040 (2007)
Yang, J. T., Preiser, A. L., Li, Z., Weise, S. E. & Sharkey, T. D. Planta 243, 687–698 (2016)
Parameters
[in] c Dimensionless scaling parameter
[in] Ha Enthalpy of activation (J / mol)
[in] Hd Enthalpy of deactivation (J / mol)
[in] S Entropy (J / K / mol)
[in] temperature_k Absolute temperature (K)
Returns
The value of a reaction rate (or some other parameter) at the specified temperature; the units of the return value will depend on the particular situation where this function is being used.
Definition at line 107 of file temperature_response_functions.h.
References arrhenius_exponential().
Referenced by c3_temperature_response().
polynomial_response()
double polynomial_response (double c0, double c1, double c2, double temperature_c) inline
A simple second-order polynomial equation describing the temperature response of a reaction rate or other parameter.
Parameters
[in] c0 The zeroth-order coefficient, in the same units as the output value
[in] c1 The first-order coefficient, in units of (output units) / (degrees C)
[in] c2 The second-order coefficient, in units of (output units) / (degrees C)^2
[in] temperature_c Temperature (degrees C)
Definition at line 142 of file temperature_response_functions.h.
Referenced by c3_temperature_response().
Q10_temperature_response()
double Q10_temperature_response (double temperature, double Tref) inline
A typical Q10-based temperature response. The two temperatures below must be supplied in the same units, but the units can be either K or degrees C.
Parameters
[in] temperature Temperature (K or degrees C)
[in] Tref Reference temperature (K or degrees C)
Returns
A scaling factor
Sources
https://doi.org/10.1016/j.fcr.2010.07.007
Definition at line 65 of file temperature_response_functions.h.
Referenced by growth_resp_Q10(), and maintenance_resp_Q10().