<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title>The `time` variable in BioCro — Time Variable • BioCro</title><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet"><script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet"><link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet"><script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="The `time` variable in BioCro — Time Variable"><meta name="description" content="Even when using an adaptive ODE solver, run_biocro returns values at
  evenly spaced time intervals given by the `timestep` parameter. It is assumed
  that the drivers are provided at intervals spaced by this `timestep`. To prevent
  user error, run_biocro will check that the `drivers“ are spaced by `timestep`
  but to do so, the `drivers` must contain a `time`."><meta property="og:description" content="Even when using an adaptive ODE solver, run_biocro returns values at
  evenly spaced time intervals given by the `timestep` parameter. It is assumed
  that the drivers are provided at intervals spaced by this `timestep`. To prevent
  user error, run_biocro will check that the `drivers“ are spaced by `timestep`
  but to do so, the `drivers` must contain a `time`."></head><body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-primary" data-bs-theme="dark" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">BioCro</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">3.2.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto"><li class="nav-item"><a class="nav-link" href="../about_pkgdown_documentation.html">About</a></li>
<li class="active nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles"><li><h6 class="dropdown-header" data-toc-skip>GENERAL BIOCRO USAGE</h6></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="../articles/BioCro.html">Getting Started with BioCro (HTML)</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/a_practical_guide_to_biocro.pdf">A Practical Guide to BioCro (PDF)</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/a_practical_guide_to_biocro.R">    [R code]</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/quantitative_model_comparison.pdf">Quantitative Comparison Between Two Photosynthesis Models (PDF)</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/quantitative_model_comparison.R">    [R code]</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/BioCro-II_Paper--Section-1.1-example.html">BioCro II Paper: Section 1.1 Example (HTML)</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/dynamical_systems.pdf">BioCro as a Dynamical System</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/an_introduction_to_biocro.pdf">An Introduction to BioCro for Those Who Want to Add Models (PDF)</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>CROP GROWTH MODELING TOPICS</h6></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="../articles/web_only/avoiding_pitfalls_fvcb.html">Avoiding Pitfalls When Using the FvCB Model (HTML)</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/thick_layer_absorption.html">Light Absorption by a Thick Layer (HTML)</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/ball_berry_model.html">Using the Ball-Berry Model (HTML)</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/canopy_photosynthesis.html">Multi-layer Canopy Photosynthesis Models (HTML)</a></li>
    <li><a class="dropdown-item" href="../articles/web_only/energy_balance.html">Energy Balance, Leaf Temperature, and Transpiration (HTML)</a></li>
  </ul></li>
<li class="nav-item"><a class="nav-link" href="../../bookdown/index.html">Developer's Manual</a></li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
<li class="nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-c-library" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">C++ Library</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-c-library"><li><a class="dropdown-item" href="../../doxygen/doxygen_docs_complete/index.html">Complete Doxygen Documentation</a></li>
    <li><a class="dropdown-item" href="../../doxygen/doxygen_docs_framework/index.html">Framework Documentation</a></li>
    <li><a class="dropdown-item" href="../../doxygen/doxygen_docs_modules/index.html">BioCro Module Documentation</a></li>
    <li><a class="dropdown-item" href="../../doxygen/doxygen_docs_modules_public_members_only/index.html">BioCro Module Documentation (public members only)</a></li>
  </ul></li>
      </ul><ul class="navbar-nav"><li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json"></form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/biocro/biocro/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul></div>


  </div>
</nav><div class="container template-reference-topic">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">

      <h1>The `time` variable in BioCro</h1>

      <div class="d-none name"><code>time_variable.rd</code></div>
    </div>

    <div class="ref-description section level2">
    <p>Even when using an adaptive ODE solver, <code>run_biocro</code> returns values at
  evenly spaced time intervals given by the `timestep` parameter. It is assumed
  that the drivers are provided at intervals spaced by this `timestep`. To prevent
  user error, <code>run_biocro</code> will check that the `drivers“ are spaced by `timestep`
  but to do so, the `drivers` must contain a `time`.</p>
    </div>


    <div class="section level2">
    <h2 id="details">Details<a class="anchor" aria-label="anchor" href="#details"></a></h2>
    <p>When differential modules are passed, BioCro will check that the drivers
    have a `time` variable that satisfies: `time[n+1] - time[n] = timestep`
    for all `n` (no checks are required for direct_modules). BioCro assumes
    that differential modules return rates-of-change in the same units as
    `timestep`.</p>
<p>Unless using modules which require time to correpond to a calendar time
    (a date and time), the starting `time[1]` has no special meaning.
    If `time[1] = 0` then `time` is the amount of time that has passed
    since the simulation's start (in the same units as `timestep`).</p>
<p>Certain modules expect `time` to specify a date and time with respect to the
    calendar. For most BioCro simulations, the rates of change are measured
    per hour, therefore `timestep` has units hour.</p>
<p>Therefore, the time variable is defined as the number of hours that
    have passed since midnight January 1st of the same year. For example
    for year 2023:
     + `time = 0` is '2023-01-01 00:00:00'
     + `time = 1` is '2023-01-01 01:00:00'
     + `time = 50`is '2023-01-03 02:00:00'
    Note in version 3.1.3 and earlier of BioCro `time` counted the number
    of days rather than hours.</p>
    </div>

  </main></div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by Justin M. McGrath, Edward B. Lochocki, Yufeng He, Scott W. Oswald, Scott Rohde, Deepak Jaiswal, Megan L. Matthews, Fernando E. Miguez, Stephen P. Long.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.1.</p>
</div>

    </footer></div>





  </body></html>

