The BioCro C++ Library: /github/workspace/src/module_library/c3_temperature_response.h File Reference
c3_temperature_response.h File Reference
Classes
struct c3_temperature_response_parameters
struct c3_param_at_tleaf
Functions
c3_param_at_tleaf c3_temperature_response (c3_temperature_response_parameters param, double Tleaf)
Calculates the values of key C3 photosynthesis parameters at leaf temperature.
Function Documentation
c3_temperature_response()
c3_param_at_tleaf c3_temperature_response (c3_temperature_response_parameters param, double Tleaf)
Calculates the values of key C3 photosynthesis parameters at leaf temperature.
The following parameters are calculated using an Arrhenius temperature response (arrhenius_exponential()) as in Bernacchi et al. (2001) and Bernacchi et al. (2003):
Gstar
Jmax_norm
Kc
Ko
Rd_norm
Vcmax_norm
The following parameters are calculated using a second-order polynomial temperature response (polynomial_response()) as in Bernacchi et al. (2001):
phi_PSII
theta
The following parameters are calculated using a Johnson, Eyring, & Williams temperature response (johnson_eyring_williams_response()) as in Harley et al. (1992):
TPU_norm
References:
Harley, P. C., Thomas, R. B., Reynolds, J. F. & Strain, B. R. Plant, Cell & Environment 15, 271–282 (1992)
Bernacchi, C. J., Singsaas, E. L., Pimentel, C., Jr, A. R. P. & Long, S. P. Plant, Cell & Environment 24, 253–259 (2001)
Bernacchi, C. J., Pimentel, C. & Long, S. P. Plant, Cell & Environment 26, 1419–1430 (2003)
Definition at line 44 of file c3_temperature_response.cpp.
References arrhenius_exponential(), conversion_constants::celsius_to_kelvin, c3_temperature_response_parameters::Gstar_c, c3_temperature_response_parameters::Gstar_Ea, c3_temperature_response_parameters::Jmax_c, c3_temperature_response_parameters::Jmax_Ea, johnson_eyring_williams_response(), c3_temperature_response_parameters::Kc_c, c3_temperature_response_parameters::Kc_Ea, c3_temperature_response_parameters::Ko_c, c3_temperature_response_parameters::Ko_Ea, c3_temperature_response_parameters::phi_PSII_0, c3_temperature_response_parameters::phi_PSII_1, c3_temperature_response_parameters::phi_PSII_2, polynomial_response(), c3_temperature_response_parameters::Rd_c, c3_temperature_response_parameters::Rd_Ea, c3_temperature_response_parameters::theta_0, c3_temperature_response_parameters::theta_1, c3_temperature_response_parameters::theta_2, c3_temperature_response_parameters::Tp_c, c3_temperature_response_parameters::Tp_Ha, c3_temperature_response_parameters::Tp_Hd, c3_temperature_response_parameters::Tp_S, c3_temperature_response_parameters::Vcmax_c, and c3_temperature_response_parameters::Vcmax_Ea.
Referenced by c3photoC(), and c3_parameters::do_operation().