The BioCro C++ Library: /github/workspace/src/module_library/boundary_layer_conductance.h File Reference
boundary_layer_conductance.h File Reference
Functions
double leaf_boundary_layer_conductance_campbell (double air_temperature, double delta_t, double lw, double windspeed, double p)
Calculates the conductance for water vapor flow from the leaf across its boundary layer using a model described in Campbell & Norman (1998).
double leaf_boundary_layer_conductance_nikolov (double air_temperature, double delta_t, double ea, double gsv, double lw, double windspeed, double p)
Calculates the conductance for water vapor flow from the leaf across its boundary layer using a model described in Nikolov, Massman, and Schoettle (1995).
double canopy_boundary_layer_conductance_thornley (double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight)
Calculates the conductance for water vapor flow from the canopy across its boundary layer using a model described in Thornley and Johnson (1990).
Function Documentation
canopy_boundary_layer_conductance_thornley()
double canopy_boundary_layer_conductance_thornley (double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight)
Calculates the conductance for water vapor flow from the canopy across its boundary layer using a model described in Thornley and Johnson (1990).
Note that when gas exchange is considered at the canopy level, this conductance characterizes the entire path to the ambient air. For a leaf within a canopy, there is an additional boundary layer separating the leaf from the canopy boundary layer; this leaf boundary layer conductance must be calculated using a separate model.
This model considers gas flow due to wind-driven eddy currents. Here, the conductance is calculated using Equation 14.9 from pages 414 - 416 of the Thornley textbook. Unfortunately, an electronic version of this reference is not available.
In this model, the minimum possible boundary layer conductance that could occur is zero, which would correspond to zero wind speed or canopy height. In realistic field conditions, boundary layer conductance can never truly be zero because of other transport processes such as buoyancy effects. To accomodate this, an option is provided for setting a minimum value for the boundary layer counductance.
This model contains two singularities, which occur when either of the following conditions are met:
WindSpeedHeight + Zeta - d = 0, which is equivalent to CanopyHeight = WindSpeedHeight / (dCoef - ZetaCoef) = WindSpeedHeight * 1.34
WindSpeedHeight + ZetaM - d = 0, which is equivalent to CanopyHeight = WindSpeedHeight / (dCoef - ZetaMCoef) = WindSpeedHeight * 1.56
So, as the canopy height approaches or exceeds the height at which wind speed was measured, the calculated boundary layer conductance becomes unbounded. For even larger canopy heights, the conductance eventually begins to decrease. For tall crops, this is a severe limitation to this model. Here we address this issue by limiting the canopy height to 0.98 * WindSpeedHeight.
References:
Thornley, J. H. M. & Johnson, I. R. "Plant and Crop Modelling: A Mathematical Approach to Plant and Crop Physiology" (1990)
Parameters
[in] CanopyHeight The height of the canopy above the ground in m
[in] WindSpeed The wind speed in m / s as measured above the canopy boundary layer
[in] minimum_gbw The lowest possible value for boundary layer conductance in m / s that should be returned
[in] WindSpeedHeight The height in m at which the wind speed was measured
Returns
The canopy boundary layer conductance in m / s
Definition at line 258 of file boundary_layer_conductance.cpp.
Referenced by canopy_gbw_thornley::do_operation(), leaf_evapotranspiration::do_operation(), and leaf_evapotranspiration_check::do_operation().
leaf_boundary_layer_conductance_campbell()
double leaf_boundary_layer_conductance_campbell (double air_temperature, double delta_t, double lw, double windspeed, double p)
Calculates the conductance for water vapor flow from the leaf across its boundary layer using a model described in Campbell & Norman (1998).
Note that for an isolated leaf, this conductance characterizes the entire path from the leaf surface to the ambient air. For a leaf within a canopy, there is an additional boundary layer separating the canopy from the atmosphere; this canopy boundary layer conductance must be calculated using a separate model.
In this model, two types of gas flow are considered: "forced" flow driven by wind-created eddy currents and "free" flow driven by temperature-related buoyancy effects. The overall conductance is determined to be the larger of the free and forced conductances.
In this function, we use the "forced convection" and "free convection" equations for vapor transfer as shown in Table 7.6. The equations as presented in the table return "molecular" conductances in units of mol / m^2 / s. Here we convert these to "mass" conductances for consistency with leaf_boundary_layer_conductance_nikolov().
These form a simpler alterative to the model presented in leaf_boundary_layer_conductance_nikolov(). Specifically, the Campbell & Norman equations do not require an iterative method to solve.
References:
Campbell, G. S. & Norman, J. "An Introduction to Environmental Biophysics," Springer-Verlag, New York, 1998
Parameters
[in] air_temperature The air temperature in degrees C
[in] delta_t The temperature difference between the leaf and air in degrees C
[in] lw The characteristic leaf dimension in m
[in] windspeed The wind speed just outside the leaf boundary layer in m / s
[in] p The atmospheric pressure in Pa
Returns
The leaf boundary layer conductance in m / s
Definition at line 52 of file boundary_layer_conductance.cpp.
References g_to_mass().
Referenced by calculate_gbw_leaf(), and leaf_gbw_campbell::do_operation().
leaf_boundary_layer_conductance_nikolov()
double leaf_boundary_layer_conductance_nikolov (double air_temperature, double delta_t, double ea, double gsv, double lw, double windspeed, double p)
Calculates the conductance for water vapor flow from the leaf across its boundary layer using a model described in Nikolov, Massman, and Schoettle (1995).
Note that for an isolated leaf, this conductance characterizes the entire path from the leaf surface to the ambient air. For a leaf within a canopy, there is an additional boundary layer separating the canopy from the atmosphere; this canopy boundary layer conductance must be calculated using a separate model.
In this model, two types of gas flow are considered: "forced" flow driven by wind-created eddy currents and "free" flow driven by temperature-related buoyancy effects. The overall conductance is determined to be the larger of the free and forced conductances.
In this function, we use equations 29, 33, 34, and 35 to calculate boundary layer conductance. This is the same approach taken in the MLcan model of Drewry et al. (2010).
Nikolov et al. (1995) solve the coupled equations for free boundary layer conductance using the fixed-point iteration method. Here we use the Dekker method for better stability.
Use this model with caution; it is know to exhibit multiple solutions, which can make its outputs discontinuous as inputs are varied.
References:
[Nikolov, N. T., Massman, W. J. & Schoettle, A. W. "Coupling biochemical and biophysical processes at the leaf level: an equilibrium photosynthesis model for leaves of C3 plants" Ecological Modelling 80, 205–235 (1995)] (https://doi.org/10.1016/0304-3800(94)00072-P)
[Drewry, D. T. et al. "Ecohydrological responses of dense canopies to environmental variability: 1. Interplay between vertical structure and photosynthetic pathway" Journal of Geophysical Research: Biogeosciences 115, (2010)] (https://doi.org/10.1029/2010JG001340)
Parameters
[in] air_temperature The air temperature in degrees C
[in] delta_t The temperature difference between the leaf and air in degrees C
[in] ea The partial pressure of water vapor in the atmosphere in Pa
[in] gsv The stomatal conductance in m / s
[in] lw The characteristic leaf dimension in m
[in] windspeed The wind speed just outside the leaf boundary layer in m / s
[in] p The atmospheric pressure in Pa
Returns
The leaf boundary layer conductance in m / s
Definition at line 130 of file boundary_layer_conductance.cpp.
References conversion_constants::celsius_to_kelvin, and saturation_vapor_pressure().
Referenced by leaf_gbw_nikolov::do_operation().