The BioCro C++ Library: leaf_evapotranspiration_check Class Reference
leaf_evapotranspiration_check Class Reference
Uses check_leaf_temp() to calculate a temperature difference.
#include <leaf_evapotranspiration_check.h>
Public Member Functions
leaf_evapotranspiration_check (state_map const &input_quantities, state_map *output_quantities)
Public Member Functions inherited from direct_module
direct_module (bool requires_euler=false)
virtual ~direct_module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
Public Member Functions inherited from module
module (bool const &differential, bool const &requires_euler)
virtual ~module ()=0
A destructor must be defined, and since the default is overridden when defining it as pure virtual, add an inline one in the header.
bool is_differential () const
bool requires_euler_ode_solver () const
void run () const
Static Public Member Functions
static string_vector get_inputs ()
static string_vector get_outputs ()
static std::string get_name ()
Private Member Functions
void do_operation () const
Private Attributes
double const & absorbed_shortwave
double const & atmospheric_pressure
double const & canopy_height
double const & Gs
double const & leaf_temperature
double const & leafwidth
double const & min_gbw_canopy
double const & rh
double const & temp
double const & wind_speed_height
double const & windspeed
double * leaf_temp_check_op
Additional Inherited Members
Protected Member Functions inherited from direct_module
void update (double *output_ptr, const double &value) const
In a valid dynamical_system object, a given quantity may be defined by only one direct module. Thus the value at output_ptr will only be writable from a single module, and we can overwrite any previously stored value.
virtual void update (double *output_ptr, const double &value) const =0
Detailed Description
Uses check_leaf_temp() to calculate a temperature difference.
This module is not intended for use in crop models. Rather, it enables investigations into the leaf energy balance equations. To solve them, a value of leaf_temperature must be found such that leaf_temp_check is zero. See leaf_energy_balance() for more information.
Definition at line 21 of file leaf_evapotranspiration_check.h.
Constructor & Destructor Documentation
leaf_evapotranspiration_check()
leaf_evapotranspiration_check (state_map const & input_quantities, state_map * output_quantities) inline
Definition at line 24 of file leaf_evapotranspiration_check.h.
Member Function Documentation
do_operation()
void do_operation () const private virtual
Implements module.
Definition at line 93 of file leaf_evapotranspiration_check.h.
References leaf_evapotranspiration_check::absorbed_shortwave, leaf_evapotranspiration_check::atmospheric_pressure, canopy_boundary_layer_conductance_thornley(), leaf_evapotranspiration_check::canopy_height, conversion_constants::celsius_to_kelvin, check_leaf_temp(), dry_air_density(), leaf_evapotranspiration_check::Gs, leaf_evapotranspiration_check::leaf_temp_check_op, leaf_evapotranspiration_check::leaf_temperature, leaf_evapotranspiration_check::leafwidth, leaf_evapotranspiration_check::min_gbw_canopy, leaf_evapotranspiration_check::rh, saturation_vapor_pressure(), physical_constants::stefan_boltzmann, leaf_evapotranspiration_check::temp, TempToCp(), TempToSFS(), direct_module::update(), vapor_density_from_pressure(), water_latent_heat_of_vaporization_henderson(), leaf_evapotranspiration_check::wind_speed_height, and leaf_evapotranspiration_check::windspeed.
get_inputs()
string_vector get_inputs () static
Definition at line 69 of file leaf_evapotranspiration_check.h.
get_name()
static std::string get_name () inline static
Definition at line 46 of file leaf_evapotranspiration_check.h.
get_outputs()
string_vector get_outputs () static
Definition at line 86 of file leaf_evapotranspiration_check.h.
Member Data Documentation
absorbed_shortwave
double const& absorbed_shortwave private
Definition at line 50 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
atmospheric_pressure
double const& atmospheric_pressure private
Definition at line 51 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
canopy_height
double const& canopy_height private
Definition at line 52 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
Gs
double const& Gs private
Definition at line 53 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
leaf_temp_check_op
double* leaf_temp_check_op private
Definition at line 63 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
leaf_temperature
double const& leaf_temperature private
Definition at line 54 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
leafwidth
double const& leafwidth private
Definition at line 55 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
min_gbw_canopy
double const& min_gbw_canopy private
Definition at line 56 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
rh
double const& rh private
Definition at line 57 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
temp
double const& temp private
Definition at line 58 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
wind_speed_height
double const& wind_speed_height private
Definition at line 59 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
windspeed
double const& windspeed private
Definition at line 60 of file leaf_evapotranspiration_check.h.
Referenced by leaf_evapotranspiration_check::do_operation().
The documentation for this class was generated from the following file:
/github/workspace/src/module_library/leaf_evapotranspiration_check.h