The BioCro C++ Library: /github/workspace/src/module_library/CanAC.cpp File Reference
CanAC.cpp File Reference
#include <algorithm>
#include <vector>
#include "../framework/constants.h"
#include "BioCro.h"
#include "c4photo.h"
#include "leaf_energy_balance.h"
#include "lightME.h"
#include "respiration.h"
#include "sunML.h"
#include "CanAC.h"
Functions
canopy_photosynthesis_outputs CanAC (const nitroParms &nitroP, double absorbed_longwave, double Alpha, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta, double Catm, double chil, double cosine_zenith_angle, double gbw_canopy, double growth_respiration_fraction, double Gs_min, double k_diffuse, double Kparm, double kpLN, double LAI, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double leafN, double leafwidth, double lowerT, double par_energy_content, double par_energy_fraction, double RH, double RL_at_25, double solarR, double StomataWS, double theta, double upperT, double Vcmax_at_25, double WindSpeed, int lnfun, int nlayers)
Function Documentation
CanAC()
canopy_photosynthesis_outputs CanAC (const nitroParms & nitroP, double absorbed_longwave, double Alpha, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta, double Catm, double chil, double cosine_zenith_angle, double gbw_canopy, double growth_respiration_fraction, double Gs_min, double k_diffuse, double Kparm, double kpLN, double LAI, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double leafN, double leafwidth, double lowerT, double par_energy_content, double par_energy_fraction, double RH, double RL_at_25, double solarR, double StomataWS, double theta, double upperT, double Vcmax_at_25, double WindSpeed, int lnfun, int nlayers)
Definition at line 12 of file CanAC.cpp.
References nitroParms::alphab0, nitroParms::alphab1, photosynthesis_outputs::Assim, c4photoC(), energy_balance_outputs::Deltat, Light_model::diffuse_fraction, Light_model::direct_fraction, energy_balance_outputs::EPenman, energy_balance_outputs::EPriestly, energy_balance_outputs::gbw_molecular, photosynthesis_outputs::GrossAssim, growth_resp(), photosynthesis_outputs::Gs, leaf_energy_balance(), lightME(), LNprof(), physical_constants::molar_mass_of_water, nitroParms::Rdb0, nitroParms::Rdb1, photosynthesis_outputs::RL, photosynthesis_outputs::Rp, Light_profile::shaded_absorbed_shortwave, Light_profile::shaded_fraction, Light_profile::shaded_incident_ppfd, Light_profile::sunlit_absorbed_shortwave, Light_profile::sunlit_fraction, Light_profile::sunlit_incident_ppfd, sunML(), energy_balance_outputs::TransR, nitroParms::Vmaxb0, nitroParms::Vmaxb1, and WINDprof().
Referenced by c4_canopy::do_operation().