The BioCro C++ Library: /github/workspace/src/module_library/c3photo.cpp File Reference
c3photo.cpp File Reference
#include <algorithm>
#include <cmath>
#include <limits>
#include "../framework/constants.h"
#include "ball_berry_gs.h"
#include "c3_temperature_response.h"
#include "conductance_helpers.h"
#include "conductance_limited_assim.h"
#include "FvCB_assim.h"
#include "../math/roots/onedim/dekker.h"
#include "c3photo.h"
Functions
photosynthesis_outputs c3photoC (c3_temperature_response_parameters const tr_param, double const absorbed_ppfd, double const Tleaf, double const Tambient, double const RH, double const Vcmax_at_25, double const Jmax_at_25, double const TPU_rate_max, double const RL_at_25, double const b0, double const b1, double const Gs_min, double const Ca, double const AP, double const O2, double const StomWS, double const electrons_per_carboxylation, double const electrons_per_oxygenation, double const beta_PSII, double const gbw)
double solo (double LeafT)
Function Documentation
c3photoC()
photosynthesis_outputs c3photoC (c3_temperature_response_parameters const tr_param, double const absorbed_ppfd, double const Tleaf, double const Tambient, double const RH, double const Vcmax_at_25, double const Jmax_at_25, double const TPU_rate_max, double const RL_at_25, double const b0, double const b1, double const Gs_min, double const Ca, double const AP, double const O2, double const StomWS, double const electrons_per_carboxylation, double const electrons_per_oxygenation, double const beta_PSII, double const gbw)
Definition at line 25 of file c3photo.cpp.
References FvCB_outputs::An, ball_berry_gs(), c3_temperature_response(), conductance_limited_assim(), stomata_outputs::cs, physical_constants::dr_boundary, physical_constants::dr_stomata, FvCB_assim(), c3_param_at_tleaf::Gstar, stomata_outputs::gsw, stomata_outputs::hs, c3_param_at_tleaf::Jmax_norm, c3_param_at_tleaf::Kc, c3_param_at_tleaf::Ko, c3_param_at_tleaf::phi_PSII, c3_param_at_tleaf::RL_norm, sequential_conductance(), solo(), c3_param_at_tleaf::theta, c3_param_at_tleaf::Tp_norm, FvCB_outputs::Vc, and c3_param_at_tleaf::Vcmax_norm.
Referenced by c3CanAC(), c3_assimilation::do_operation(), and c3_leaf_photosynthesis::do_operation().
solo()
double solo (double LeafT)
Definition at line 192 of file c3photo.cpp.
Referenced by c3photoC().