var searchData=
[
  ['c3_5fassimilation_0',['c3_assimilation',['../classstandard_b_m_l_1_1c3__assimilation.html#a5a0dff890013571b995ee3cc09d03f9e',1,'standardBML::c3_assimilation']]],
  ['c3_5fcanopy_1',['c3_canopy',['../classstandard_b_m_l_1_1c3__canopy.html#af90d78d048115ea86b02a3d2183756d8',1,'standardBML::c3_canopy']]],
  ['c3_5fleaf_5fphotosynthesis_2',['c3_leaf_photosynthesis',['../classstandard_b_m_l_1_1c3__leaf__photosynthesis.html#ae71f3cdfe179f53d0ea5785475d10dca',1,'standardBML::c3_leaf_photosynthesis']]],
  ['c3_5fparameters_3',['c3_parameters',['../classstandard_b_m_l_1_1c3__parameters.html#a9c346320241c303a854ff62470ad69ef',1,'standardBML::c3_parameters']]],
  ['c3_5ftemperature_5fresponse_4',['c3_temperature_response',['../c3__temperature__response_8h.html#a69f1af5907ee319a7b914a946909fba4',1,'c3_temperature_response(c3_temperature_response_parameters param, double Tleaf):&#160;c3_temperature_response.cpp'],['../c3__temperature__response_8cpp.html#a69f1af5907ee319a7b914a946909fba4',1,'c3_temperature_response(c3_temperature_response_parameters param, double Tleaf):&#160;c3_temperature_response.cpp']]],
  ['c3canac_5',['c3CanAC',['../c3_can_a_c_8h.html#a5c0f82c3a7a653e572bbaee3b22cbfa0',1,'c3CanAC(c3_temperature_response_parameters const tr_param, double absorbed_longwave, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta_PSII, double Catm, double chil, double cosine_zenith_angle, double electrons_per_carboxylation, double electrons_per_oxygenation, double gbw_canopy, double growth_respiration_fraction, double Gs_min, double heightf, double Jmax, double kpLN, double k_diffuse, double LAI, double leafN, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double leaf_width, double lnb0, double lnb1, double o2, double par_energy_content, double par_energy_fraction, double Rd, double RH, double solarR, double StomataWS, double tpu_rate_max, double Vmax, double WindSpeed, double WindSpeedHeight, int lnfun, int nlayers):&#160;c3CanAC.cpp'],['../c3_can_a_c_8cpp.html#a5c0f82c3a7a653e572bbaee3b22cbfa0',1,'c3CanAC(c3_temperature_response_parameters const tr_param, double absorbed_longwave, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta_PSII, double Catm, double chil, double cosine_zenith_angle, double electrons_per_carboxylation, double electrons_per_oxygenation, double gbw_canopy, double growth_respiration_fraction, double Gs_min, double heightf, double Jmax, double kpLN, double k_diffuse, double LAI, double leafN, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double leaf_width, double lnb0, double lnb1, double o2, double par_energy_content, double par_energy_fraction, double Rd, double RH, double solarR, double StomataWS, double tpu_rate_max, double Vmax, double WindSpeed, double WindSpeedHeight, int lnfun, int nlayers):&#160;c3CanAC.cpp']]],
  ['c3photoc_6',['c3photoC',['../c3photo_8cpp.html#a4d07b25f5d749afc444dec66e66af256',1,'c3photoC(c3_temperature_response_parameters const tr_param, double const absorbed_ppfd, double const Tleaf, double const Tambient, double const RH, double const Vcmax0, double const Jmax0, double const TPU_rate_max, double const Rd0, double const b0, double const b1, double const Gs_min, double const Ca, double const AP, double const O2, double const StomWS, double const electrons_per_carboxylation, double const electrons_per_oxygenation, double const beta_PSII, double const gbw):&#160;c3photo.cpp'],['../c3photo_8h.html#a7d7632507b5b92618a5d48698006afac',1,'c3photoC(c3_temperature_response_parameters const tr_param, double const absorbed_ppfd, double const Tleaf, double const Tambient, double const RH, double const Vcmax0, double const Jmax0, double const TPU_rate_max, double const Rd0, double const bb0, double const bb1, double const Gs_min, double Ca, double const AP, double const O2, double const StomWS, double const electrons_per_carboxylation, double const electrons_per_oxygenation, double const beta_PSII, double const gbw):&#160;c3photo.cpp']]],
  ['c4_5fassimilation_7',['c4_assimilation',['../classstandard_b_m_l_1_1c4__assimilation.html#adc6d82ea8fdc264efdb6ea20f943738c',1,'standardBML::c4_assimilation']]],
  ['c4_5fcanopy_8',['c4_canopy',['../classstandard_b_m_l_1_1c4__canopy.html#a94d23dfe2a067f56b731d38f379f2d9c',1,'standardBML::c4_canopy']]],
  ['c4_5fleaf_5fphotosynthesis_9',['c4_leaf_photosynthesis',['../classstandard_b_m_l_1_1c4__leaf__photosynthesis.html#ab4a252ecfb25a713e36d6af419915e79',1,'standardBML::c4_leaf_photosynthesis']]],
  ['c4photoc_10',['c4photoC',['../c4photo_8cpp.html#a0ac8af0343c49f4ab5cf95fe21333179',1,'c4photoC(double const Qp, double const leaf_temperature, double const ambient_temperature, double const relative_humidity, double const vmax, double const alpha, double const kparm, double const theta, double const beta, double const Rd, double const bb0, double const bb1, double const Gs_min, double const StomaWS, double const Ca, double const atmospheric_pressure, double const upperT, double const lowerT, double const gbw):&#160;c4photo.cpp'],['../c4photo_8h.html#a0ac8af0343c49f4ab5cf95fe21333179',1,'c4photoC(double const Qp, double const leaf_temperature, double const ambient_temperature, double const relative_humidity, double const vmax, double const alpha, double const kparm, double const theta, double const beta, double const Rd, double const bb0, double const bb1, double const Gs_min, double const StomaWS, double const Ca, double const atmospheric_pressure, double const upperT, double const lowerT, double const gbw):&#160;c4photo.cpp']]],
  ['canac_11',['CanAC',['../_can_a_c_8cpp.html#a9f9b5bd73a96f6f6a324fcb79b5f8386',1,'CanAC(const nitroParms &amp;nitroP, double absorbed_longwave, double Alpha, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta, double Catm, double chil, double cosine_zenith_angle, double gbw_canopy, double Gs_min, double Kparm, double kpLN, double k_diffuse, double LAI, double leafN, double leafwidth, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double lowerT, double par_energy_content, double par_energy_fraction, double Rd, double RH, double solarR, double StomataWS, double theta, double upperT, double Vmax, double WindSpeed, int lnfun, int nlayers):&#160;CanAC.cpp'],['../_can_a_c_8h.html#a9f9b5bd73a96f6f6a324fcb79b5f8386',1,'CanAC(const nitroParms &amp;nitroP, double absorbed_longwave, double Alpha, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta, double Catm, double chil, double cosine_zenith_angle, double gbw_canopy, double Gs_min, double Kparm, double kpLN, double k_diffuse, double LAI, double leafN, double leafwidth, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double lowerT, double par_energy_content, double par_energy_fraction, double Rd, double RH, double solarR, double StomataWS, double theta, double upperT, double Vmax, double WindSpeed, int lnfun, int nlayers):&#160;CanAC.cpp']]],
  ['canopy_5fboundary_5flayer_5fconductance_5fthornley_12',['canopy_boundary_layer_conductance_thornley',['../boundary__layer__conductance_8h.html#a8a0c037ff31b377084680a25728ed4ec',1,'canopy_boundary_layer_conductance_thornley(double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight):&#160;boundary_layer_conductance.cpp'],['../boundary__layer__conductance_8cpp.html#a8a0c037ff31b377084680a25728ed4ec',1,'canopy_boundary_layer_conductance_thornley(double CanopyHeight, double WindSpeed, double minimum_gbw, double WindSpeedHeight):&#160;boundary_layer_conductance.cpp']]],
  ['canopy_5fgbw_5fthornley_13',['canopy_gbw_thornley',['../classstandard_b_m_l_1_1canopy__gbw__thornley.html#a5f948a17083a468d3e3acc577ef08fd8',1,'standardBML::canopy_gbw_thornley']]],
  ['carbon_5fassimilation_5fto_5fbiomass_14',['carbon_assimilation_to_biomass',['../classstandard_b_m_l_1_1carbon__assimilation__to__biomass.html#a855082a7fdc4abcc77385210ca35eb90',1,'standardBML::carbon_assimilation_to_biomass']]],
  ['collatz_5fphoto_15',['collatz_photo',['../collatz__photo_8cpp.html#a8b6ed801aeda3fb4d6de7aae13664d73',1,'collatz_photo(double Qp, double leaf_temperature, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double upperT, double lowerT, double k_Q10, double intercellular_co2_molar_fraction):&#160;collatz_photo.cpp'],['../collatz__photo_8h.html#a8b6ed801aeda3fb4d6de7aae13664d73',1,'collatz_photo(double Qp, double leaf_temperature, double vmax, double alpha, double kparm, double theta, double beta, double Rd, double upperT, double lowerT, double k_Q10, double intercellular_co2_molar_fraction):&#160;collatz_photo.cpp']]],
  ['compute_5fwsphoto_16',['compute_wsPhoto',['../_aux_bio_cro_8cpp.html#a058be0e6ed718b377d7c6056cceb09a8',1,'AuxBioCro.cpp']]],
  ['conductance_5flimited_5fassim_17',['conductance_limited_assim',['../conductance__limited__assim_8h.html#a9912249fe80a1a615d0316c7778cd6cf',1,'conductance_limited_assim.h']]]
];
