The BioCro C++ Library: /github/workspace/src/module_library/c3CanAC.h File Reference
c3CanAC.h File Reference
#include "canopy_photosynthesis_outputs.h"
#include "c3_temperature_response.h"
Functions
canopy_photosynthesis_outputs c3CanAC (c3_temperature_response_parameters const tr_param, double absorbed_longwave, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta_PSII, double Catm, double chil, double cosine_zenith_angle, double electrons_per_carboxylation, double electrons_per_oxygenation, double gbw_canopy, double growth_respiration_fraction, double Gs_min, double heightf, double Jmax_at_25, double k_diffuse, double kpLN, double LAI, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double leaf_width, double leafN, double lnb0, double lnb1, double o2, double par_energy_content, double par_energy_fraction, double RH, double RL_at_25, double solarR, double StomataWS, double Tp_at_25, double Vcmax_at_25, double WindSpeed, double WindSpeedHeight, int lnfun, int nlayers)
Function Documentation
c3CanAC()
canopy_photosynthesis_outputs c3CanAC (c3_temperature_response_parameters const tr_param, double absorbed_longwave, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta_PSII, double Catm, double chil, double cosine_zenith_angle, double electrons_per_carboxylation, double electrons_per_oxygenation, double gbw_canopy, double growth_respiration_fraction, double Gs_min, double heightf, double Jmax_at_25, double k_diffuse, double kpLN, double LAI, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double leaf_width, double leafN, double lnb0, double lnb1, double o2, double par_energy_content, double par_energy_fraction, double RH, double RL_at_25, double solarR, double StomataWS, double Tp_at_25, double Vcmax_at_25, double WindSpeed, double WindSpeedHeight, int lnfun, int nlayers)
Definition at line 11 of file c3CanAC.cpp.
References photosynthesis_outputs::Assim, c3photoC(), energy_balance_outputs::Deltat, Light_model::diffuse_fraction, Light_model::direct_fraction, energy_balance_outputs::EPenman, energy_balance_outputs::EPriestly, energy_balance_outputs::gbw_molecular, photosynthesis_outputs::GrossAssim, growth_resp(), photosynthesis_outputs::Gs, leaf_energy_balance(), lightME(), LNprof(), photosynthesis_outputs::RL, photosynthesis_outputs::Rp, Light_profile::shaded_absorbed_ppfd, Light_profile::shaded_absorbed_shortwave, Light_profile::shaded_fraction, Light_profile::sunlit_absorbed_ppfd, Light_profile::sunlit_absorbed_shortwave, Light_profile::sunlit_fraction, sunML(), energy_balance_outputs::TransR, and WINDprof().