The BioCro C++ Library: /github/workspace/src/module_library/CanAC.h File Reference
CanAC.h File Reference
#include "AuxBioCro.h"
#include "canopy_photosynthesis_outputs.h"
Functions
canopy_photosynthesis_outputs CanAC (const nitroParms &nitroP, double absorbed_longwave, double Alpha, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta, double Catm, double chil, double cosine_zenith_angle, double gbw_canopy, double Gs_min, double Kparm, double kpLN, double k_diffuse, double LAI, double leafN, double leafwidth, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double lowerT, double par_energy_content, double par_energy_fraction, double Rd, double RH, double solarR, double StomataWS, double theta, double upperT, double Vmax, double WindSpeed, int lnfun, int nlayers)
Function Documentation
CanAC()
canopy_photosynthesis_outputs CanAC (const nitroParms & nitroP, double absorbed_longwave, double Alpha, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta, double Catm, double chil, double cosine_zenith_angle, double gbw_canopy, double Gs_min, double Kparm, double kpLN, double k_diffuse, double LAI, double leafN, double leafwidth, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double lowerT, double par_energy_content, double par_energy_fraction, double Rd, double RH, double solarR, double StomataWS, double theta, double upperT, double Vmax, double WindSpeed, int lnfun, int nlayers)
Definition at line 10 of file CanAC.cpp.
References nitroParms::alphab0, nitroParms::alphab1, canopy_photosynthesis_outputs::Assim, photosynthesis_outputs::Assim, c4photoC(), canopy_photosynthesis_outputs::canopy_conductance, canopy_photosynthesis_outputs::canopy_transpiration_penman, canopy_photosynthesis_outputs::canopy_transpiration_priestly, energy_balance_outputs::Deltat, Light_model::diffuse_fraction, Light_model::direct_fraction, energy_balance_outputs::EPenman, energy_balance_outputs::EPriestly, energy_balance_outputs::gbw_molecular, canopy_photosynthesis_outputs::GrossAssim, photosynthesis_outputs::GrossAssim, photosynthesis_outputs::Gs, leaf_energy_balance(), lightME(), LNprof(), nitroParms::Rdb0, nitroParms::Rdb1, canopy_photosynthesis_outputs::Rp, photosynthesis_outputs::Rp, Light_profile::shaded_absorbed_shortwave, Light_profile::shaded_fraction, Light_profile::shaded_incident_ppfd, Light_profile::sunlit_absorbed_shortwave, Light_profile::sunlit_fraction, Light_profile::sunlit_incident_ppfd, sunML(), canopy_photosynthesis_outputs::Trans, energy_balance_outputs::TransR, nitroParms::Vmaxb0, nitroParms::Vmaxb1, and WINDprof().
Referenced by c4_canopy::do_operation().