The BioCro C++ Library: /github/workspace/src/module_library/c3CanAC.cpp File Reference
c3CanAC.cpp File Reference
#include <vector>
#include "c3CanAC.h"
#include "../framework/constants.h"
#include "BioCro.h"
#include "c3photo.h"
#include "leaf_energy_balance.h"
#include "lightME.h"
#include "sunML.h"
Functions
canopy_photosynthesis_outputs c3CanAC (c3_temperature_response_parameters const tr_param, double absorbed_longwave, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta_PSII, double Catm, double chil, double cosine_zenith_angle, double electrons_per_carboxylation, double electrons_per_oxygenation, double gbw_canopy, double growth_respiration_fraction, double Gs_min, double heightf, double Jmax, double kpLN, double k_diffuse, double LAI, double leafN, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double leaf_width, double lnb0, double lnb1, double o2, double par_energy_content, double par_energy_fraction, double Rd, double RH, double solarR, double StomataWS, double tpu_rate_max, double Vmax, double WindSpeed, double WindSpeedHeight, int lnfun, int nlayers)
Function Documentation
c3CanAC()
canopy_photosynthesis_outputs c3CanAC (c3_temperature_response_parameters const tr_param, double absorbed_longwave, double ambient_temperature, double atmospheric_pressure, double atmospheric_scattering, double atmospheric_transmittance, double b0, double b1, double beta_PSII, double Catm, double chil, double cosine_zenith_angle, double electrons_per_carboxylation, double electrons_per_oxygenation, double gbw_canopy, double growth_respiration_fraction, double Gs_min, double heightf, double Jmax, double kpLN, double k_diffuse, double LAI, double leafN, double leaf_reflectance_nir, double leaf_reflectance_par, double leaf_transmittance_nir, double leaf_transmittance_par, double leaf_width, double lnb0, double lnb1, double o2, double par_energy_content, double par_energy_fraction, double Rd, double RH, double solarR, double StomataWS, double tpu_rate_max, double Vmax, double WindSpeed, double WindSpeedHeight, int lnfun, int nlayers)
Definition at line 10 of file c3CanAC.cpp.
References canopy_photosynthesis_outputs::Assim, photosynthesis_outputs::Assim, c3photoC(), canopy_photosynthesis_outputs::canopy_conductance, canopy_photosynthesis_outputs::canopy_transpiration_penman, canopy_photosynthesis_outputs::canopy_transpiration_priestly, energy_balance_outputs::Deltat, Light_model::diffuse_fraction, Light_model::direct_fraction, energy_balance_outputs::EPenman, energy_balance_outputs::EPriestly, energy_balance_outputs::gbw_molecular, canopy_photosynthesis_outputs::GrossAssim, photosynthesis_outputs::GrossAssim, photosynthesis_outputs::Gs, leaf_energy_balance(), lightME(), LNprof(), canopy_photosynthesis_outputs::Rp, photosynthesis_outputs::Rp, Light_profile::shaded_absorbed_ppfd, Light_profile::shaded_absorbed_shortwave, Light_profile::shaded_fraction, Light_profile::sunlit_absorbed_ppfd, Light_profile::sunlit_absorbed_shortwave, Light_profile::sunlit_fraction, sunML(), canopy_photosynthesis_outputs::Trans, energy_balance_outputs::TransR, and WINDprof().
Referenced by c3_canopy::do_operation().